// FAQ sections (For law firms, AI chatbots, Branding) and the "Starting a law firm" guide.
// Regulatory points follow the SRA's published guidance (sra.org.uk); keep them general and link out.

const faq = (h, items) => `<section class="mk-features faq-sec"><div class="mk-sec-head"><div class="mk-eyebrow">FAQs</div><h2>${h}</h2></div><div class="faq">${items.map(([q, a]) => `<details class="faq-q"><summary>${q}</summary><div class="faq-a">${a}</div></details>`).join('')}</div></section>`;
window.faq = faq;
const SRA = 'https://www.sra.org.uk';
const ext = (href, text) => `<a href="${href}" target="_blank" rel="noopener">${text}</a>`;

PAGES.legal += faq('Law firm website questions.', [
['What does the SRA require on a law firm website?', `<p>Every SRA-authorised firm with a website must display its SRA number and the SRA's clickable logo (the digital badge) in a prominent place. You also need to publish your complaints procedure, including how and when a client can complain to the Legal Ombudsman and to the SRA.</p><p>If you offer any of the services covered by the SRA Transparency Rules, you must publish price and service information for them too. We build all of this in from the start.</p>`],
['Which services need prices on the website?', `<p>The Transparency Rules cover residential conveyancing, uncontested probate, summary-only motoring offences, employment tribunal claims for unfair or wrongful dismissal (bringing or defending), immigration (excluding asylum), debt recovery up to £100,000, and licensing applications for business premises. See the SRA's ${ext(SRA + '/solicitors/guidance/transparency-in-price-and-service/', 'transparency guidance')}.</p>`],
['What price information has to be shown?', `<p>A total cost, or an average or range if that isn't possible, and the basis of your charges, such as hourly rates or fixed fees. You also need likely disbursements and whether VAT is included. Alongside the price: what is and isn't included, the key stages and typical timescales, and the experience and qualifications of the people doing the work.</p>`],
['Where should the SRA digital badge go?', `<p>Somewhere prominent. Most firms put it in the site footer so it appears on every page. The badge is a snippet of code from the SRA that shows your live regulated status, so we add the real code rather than a static image.</p>`],
['Do we need a cookie banner?', `<p>Only if your site uses cookies that aren't strictly necessary, such as analytics or marketing cookies. Those need consent first under UK privacy law (PECR). We set sites up so consent is asked for properly, or so non-essential cookies aren't needed at all.</p>`],
['Does the website have to be hosted in the UK?', `<p>The SRA doesn't require it. Keeping your site and enquiry data in the UK does keep things simpler under UK GDPR, because no international data transfers are involved. We host on our own servers in a UK data centre.</p>`],
['We\'re setting up a new firm. Where do we start?', `<p>Read our <a href="#starting-a-law-firm">guide to starting a law firm</a>. It covers authorisation, insurance, compliance roles and what your website needs on day one.</p>`],
]);

PAGES.ai += faq('AI chatbot questions.', [
['Can a law firm use an AI chatbot on its website?', `<p>Yes. The SRA's usual standards still apply: visitors shouldn't be misled, and it should be clear they're talking to an automated assistant, not a solicitor. Personal data also has to be handled in line with UK GDPR. We build the chatbot with that disclosure in place from the first message.</p>`],
['Will the chatbot give legal advice?', `<p>No. It gives general information from your own website, says that it isn't legal advice, and passes anything specific to your team.</p>`],
['Where do its answers come from?', `<p>Your site: your services, fees pages and FAQs. It points visitors to the right page rather than making things up, and it answers in your firm's voice.</p>`],
['What happens to enquiries it collects?', `<p>It takes the visitor's details and what they need, then passes them to your team so you can follow up.</p>`],
['What is "AI web design"?', `<p>It usually means one of two things: a website generated by an AI tool, or a website with AI features built in. We do the second. Every copacetic.web site is designed from a blank page around your brand, and we can add an AI chatbot trained on your content.</p>`],
['Can the chatbot go on our existing website?', `<p>Talk to us about your current site. The simplest route is usually as part of a new copacetic.web site, where the chatbot, your fees pages and your FAQs are all designed together.</p>`],
]);

PAGES.branding += faq('Branding questions for new firms.', [
['When should a new firm think about branding?', `<p>Early. You need a firm name for your SRA application, company registration and domain, so it's worth settling the name before you file anything. The logo, colours and website can follow once the name is fixed.</p>`],
['What should we check before choosing a name?', `<p>Check that it's available at Companies House (if you're incorporating), that a good .co.uk or .com domain is free, and that nobody holds a conflicting trade mark on the UK IPO register. Your name and publicity also mustn't mislead people about who you are or what you do.</p>`],
['Can you come up with the name?', `<p>Yes. We create your name, logo, colours and identity, then carry it through your website, social media and documents.</p>`],
['What do we get at the end?', `<p>A logo and wordmark, a colour palette and typefaces that work on screen and in print, and a short brand guide so everything stays consistent.</p>`],
['Do we need to register a trade mark?', `<p>It isn't required, but it's worth considering once you've settled on a name, and worth searching the register before you commit. A trade mark attorney can advise on whether registering is right for you.</p>`],
['Is there a checklist for the rest of the set-up?', `<p>Yes: our <a href="#starting-a-law-firm">guide to starting a law firm</a> covers the steps from structure and SRA authorisation to your first website.</p>`],
]);

const gsec = (n, h, body) => `<section class="guide-sec"><div class="guide-n">${n}</div><div><h2>${h}</h2>${body}</div></section>`;
const tick = items => `<ul class="guide-list">${items.map(i => `<li><i class="ti ti-circle-check"></i><span>${i}</span></li>`).join('')}</ul>`;

PAGES['starting-a-law-firm'] = hero('Guide', 'Starting a law firm in England &amp; Wales.', 'A practical checklist for solicitors setting up their own firm: structure, SRA authorisation, insurance, compliance and the website you need on day one.') + `
<div class="guide">
<p class="guide-note"><i class="ti ti-info-circle"></i><span>This is general information, not legal or regulatory advice. The SRA's own guidance is the authority: start with ${ext(SRA + '/solicitors/guidance/can-my-business-be-authorised/', 'Can my business be authorised?')}</span></p>
${gsec('01', 'Choose your structure', `<p>Decide how the firm will be set up: a sole practice, a partnership, a limited liability partnership (LLP) or a limited company. If people who aren't lawyers will own or manage the firm, you'll need to become an alternative business structure (ABS).</p><p>Not every solicitor needs a firm. Some work as freelance or consultant solicitors, or join a platform firm, instead. If that's you, see our <a href="#solicitors">solicitor profile sites</a>.</p>`)}
${gsec('02', 'Apply for SRA authorisation', `<p>New firms apply to the SRA for authorisation before they can offer regulated legal services. Among other things, the SRA will want to see:</p>${tick([
'A <strong>compliance officer for legal practice (COLP)</strong> and a <strong>compliance officer for finance and administration (COFA)</strong>, both approved by the SRA.',
'Someone to supervise the work who is a lawyer and has <strong>practised for at least three years</strong>.',
'Approval of the firm\'s owners and managers.',
'Evidence that you can get <strong>qualifying professional indemnity insurance</strong>.',
])}<p>Allow time for this. See the SRA's ${ext(SRA + '/solicitors/firm-based-authorisation/authorisation-recognition/', 'firm authorisation pages')}.</p>`)}
${gsec('03', 'Arrange professional indemnity insurance', `<p>Every SRA-authorised firm needs qualifying professional indemnity insurance from a participating insurer, on the SRA's minimum terms. A specialist broker can help you compare quotes, and you'll need evidence of cover for your application.</p>`)}
${gsec('04', 'Set up money and anti-money laundering controls', `<p>Decide how you'll handle client money: a client account under the SRA Accounts Rules, or a third-party managed account. Your COFA oversees this.</p><p>If your work falls within the Money Laundering Regulations (conveyancing, for example), you'll also need a firm-wide risk assessment, and policies, controls and procedures to match.</p>`)}
${gsec('05', 'Register the business', `<p>The practical admin:</p>${tick([
'Companies House, if you\'re an LLP or a limited company.',
'HMRC for tax, and VAT once you reach the threshold.',
'The ICO data protection fee, which most firms handling client data must pay.',
'A business bank account and practice management software.',
'A written complaints procedure that includes the Legal Ombudsman.',
])}`)}
${gsec('06', 'Build your name and brand', `<p>Settle the name early: you'll need it for your application, registration and domain. Check it's available at Companies House, as a domain and on the UK IPO trade mark register. Then build the logo, colours and identity around it. See <a href="#branding">branding for new law firms</a>.</p>`)}
${gsec('07', 'Launch a compliant website', `<p>Your website is often the first thing clients check. On day one it should have:</p>${tick([
'Your <strong>SRA number</strong> and the <strong>SRA clickable logo</strong>, displayed prominently.',
'Your <strong>complaints procedure</strong>, including how and when to complain to the Legal Ombudsman and the SRA.',
'<strong>Price and service information</strong> for any services covered by the SRA Transparency Rules.',
'Company details (name, registered number, registered office) if you\'re an LLP or company.',
'A UK GDPR privacy notice, and cookie consent if you use non-essential cookies.',
'Clear warnings about bank-detail changes, to help protect clients from payment fraud.',
'Solicitor profiles, a secure enquiry form, and pages that work on every phone.',
])}<p>We build all of this in from the start. See <a href="#legal">what we build for law firms</a>.</p>`)}
<div class="guide-cta"><div><div class="price-name">Setting up a firm?</div><div class="price-tagline">Tell us where you are with your plans. We'll help with the name, brand and website.</div></div><a class="mk-btn mk-btn-dark mk-btn-lg" href="#contact">Start a project <i class="ti ti-arrow-right"></i></a></div>
</div>`;

// Home: the philosophy statement, between "Companies we work with" and "What we do".
const TRUST_ROW = '<div class="mk-trust"><span>Companies we work with</span><div class="mk-trust-row" id="trust"></div></div>';
PAGES.home = PAGES.home.replace(TRUST_ROW, TRUST_ROW + `
<section class="mk-philo"><div class="mk-eyebrow">Our philosophy</div><p>Your website isn't just a shop window for your business or brand. It's there to tell the world about <em>you and your philosophy.</em></p></section>`);
